5 get article comments - completed challenge 6 - GET /api/article/:article_id/comments
Jookz/Jonnys-nc-news pull request #5
Opened 2023-10-03 15:26 UTC by Jookz

2023-10-03 15:41 UTC, B7Bprog requested changes
Hey Jonny, please check my comments and add those tests/refactor code, then please send this PR back to use with the updates.

2023-10-03 15:41 UTC, B7Bprog commented on __tests__/nc_news.test.js
> +            console.log(body)
Please remove all debugging logs.

2023-10-03 15:41 UTC, B7Bprog commented on __tests__/nc_news.test.js
> +    });
Please add another test for a successful response where the article exists but there are no comments for it. Responding with an empty array.

2023-10-03 15:41 UTC, B7Bprog commented on controllers/topics.controller.js
> +    fetchComments(article_id).then(({rows}) => {
You will need to check the reason for the query returning empty rows:
- article exists but has no comments.
- article does not exist.

2023-10-05 10:17 UTC, NRMSMITH approved these changes
I've asked a q about your conditional logic - please address this and then merge :)

2023-10-05 10:17 UTC, NRMSMITH commented on controllers/topics.controller.js
> +
Is this conditional logic needed? The article_id should be there - if not it won't get to this endpoint :)

2023-10-05 10:37 UTC, merged